name: pazir
description: "A new Flutter project."
publish_to: "none"
version: 1.4.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  get: 4.7.2
  flutter_inappwebview: 6.1.5
  file_picker: 10.3.7
  permission_handler: 12.0.1
  video_thumbnail: 0.5.3
  path_provider: 2.1.5
  video_player: 2.10.0
  intl: 0.20.2
  audioplayers: 6.5.1
  record: 6.1.2
  flutter_smart_dialog: 4.9.8+9
  shared_preferences: 2.5.3
  in_app_purchase: 3.2.1
  dio: 5.9.0
  encrypt: 5.0.0
  convert: 3.1.2
  loading_indicator: 3.1.1
  flutter_launcher_icons: 0.14.4
  flutter_native_splash: 2.4.7
  flutter_keychain: ^2.5.0
  vpn_detector: 1.2.0
  system_keyboard_languages: 0.0.2
  facebook_app_events: ^0.20.1
  device_info_plus: ^12.2.0
  http: 1.5.0
  screen_protector: ^1.4.2+1
  devicelocale: 0.8.2
  flutter_native_timezone: 2.0.0
  flutter_local_notifications: 19.5.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: truedevicelocale
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  image_path: "assets/images/Pazir.png"

flutter_native_splash:
  background_image: "assets/images/nxuiBASDAIUW.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/video/
    - assets/audio/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Medium.ttf
